# K Fold Cross Validation
### Evaluate  Model Performance

<img src=kfc1.png height=400 width=400>
### Taking all data for training and test is Extremely biased
<img src=kfc2.png height=400 width=400>
### Problem of trainig,test split is: It is not perfect
<img src=kfc1.png height=400 width=400>
### So, KFold Cross Validation is effecient

## Implementation

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt

In [2]:
digits = load_digits()

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

#### Logistic Regression

In [4]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9574074074074074

#### SVM

In [5]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.45185185185185184

#### Random Forest

In [6]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9629629629629629

## KFold cross validation
#### Basic example

In [7]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)          # Taking 3 split number
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)       # So, its taking 1/3rd as test data and remaining as training data for 3times

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


#### KFold for our digits example

In [9]:
def get_score(model, X_train, X_test, y_train, y_test):   # Manual function for getting model score
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [10]:
from sklearn.model_selection import StratifiedKFold  # StratifieldKFold Categorized uniform way
folds = StratifiedKFold(n_splits=3)

scores_logistic = []   # For appending model scores in list
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):          # Doing manually
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [11]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [12]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [13]:
scores_rf

[0.9315525876460768, 0.9599332220367279, 0.9098497495826378]

### cross_val_score function

In [14]:
from sklearn.model_selection import cross_val_score  # It will do above task automatically

#### Logistic regression model performance using cross_val_score

In [15]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

#### SVM model performance using cross_val_score

In [16]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

#### Random Forest performance using cross_val_score

In [17]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.92153589, 0.94490818, 0.92487479])

### Parameter Tuning

In [18]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8770546244568591

In [19]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9454562383612662