# Pickle & Joblib

#### Saving a previous model done by me

In [5]:
import pandas as pd
import numpy as np
from sklearn import linear_model

df = pd.read_csv('homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [6]:
model = linear_model.LinearRegression()      # Creating linear regression object
model.fit(df[['area']],df[['price']])        # Fitting regression object with dataset values

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [7]:
model.coef_   # m

array([[135.78767123]])

In [8]:
model.intercept_ # b

array([180616.43835616])

In [9]:
model.predict([[5000]])

array([[859554.79452055]])

### Save Model To a File Using Python Pickle

In [10]:
import pickle

with open('model_pickle','wb') as file:        # writing in binary mode
    pickle.dump(model,file)

#### Loading saved model

In [11]:
with open('model_pickle','rb') as file:
    prediction_model = pickle.load(file)

In [12]:
prediction_model.coef_

array([[135.78767123]])

In [13]:
prediction_model.intercept_

array([180616.43835616])

In [14]:
prediction_model.predict([[5000]])

array([[859554.79452055]])

### Save Model To a File Using sklearn joblib

In [15]:
from sklearn.externals import joblib

joblib.dump(model, 'model_joblib')    # joblib is more efficient when number of numpy array are huge

c:\users\shaon\appdata\local\programs\python\python37\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


['model_joblib']

#### Loading saved joblib model

In [17]:
prediction_model2= joblib.load('model_joblib')

In [18]:
prediction_model2.coef_

array([[135.78767123]])

In [19]:
prediction_model2.intercept_

array([180616.43835616])

In [20]:
prediction_model2.predict([[5000]])

array([[859554.79452055]])