# Intro
### Main Feature of numpy is n-dimensional array

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])  # It's similar to python  list

In [3]:
a[1]    # Accessing eement

2

### Benefit of numpy array over python list
#### 1. Less memory
#### 2. Fast
#### 3. Convinient

In [4]:
import sys

l=range(1000) # List of 1000 items
sys.getsizeof(5)*len(l)   # size of one element* total length

28000

In [5]:
array=np.arange(1000) # numpy array of 1000 items
array.size*array.itemsize   # total length*size of one element

4000

*** So, list took 28000 bytes whre numpy took only 4000bytes***
<img src=np1.png height=400 width=600>

In [16]:
import time

SIZE=100000000    # Taking a long size to visualize computational time
l1=range(SIZE)
l2=range(SIZE)

a1=np.arange(SIZE)
a2=np.arange(SIZE)

In [17]:
# Computation time of Python list
start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
time.time()-start*1000       # Python list took this much time for computing in milisecond

-1593975903900.0107

In [18]:
# Computation time of Numpy array
start=time.time()
result=a1+a2
time.time()-start*1000      # Numpy array took this much time for computing in milisecond

-1593975952599.982

### Computational Advantage

In [21]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])

In [22]:
a1+a2

array([5, 7, 9])

In [23]:
a1-a2

array([-3, -3, -3])

In [24]:
a2/a1

array([4. , 2.5, 2. ])