# Numpy array

In [1]:
import numpy as np

In [2]:
a=np.array([5,6,9]) # 1D array
a[1]  

6

In [6]:
b=np.array([[1,2],[3,4],[5,6]]) # 2D array

In [7]:
b.ndim     # ndim shows the dimension of numpy array

2

In [8]:
a.ndim

1

In [9]:
a.itemsize   # since it's integer values

4

In [10]:
a.dtype

dtype('int32')

In [11]:
a=np.array([5,6,9], dtype=np.float64) # changing data type to float

In [12]:
a.itemsize # Since it's float value

8

In [14]:
b.size # total elements

6

In [15]:
b.shape  # informaton of dimension

(3, 2)

In [16]:
a=np.array([5,6,9], dtype=np.complex)  # complex number
a

array([5.+0.j, 6.+0.j, 9.+0.j])

In [17]:
# initialize array with all zeroes
np.zeros((3,4))   # shape as parameter

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((3,5))   # shape as parameter

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
l=range(5)  # list of 5 elements 0 t0 4(0,1,2,3,4)
l

range(0, 5)

In [21]:
np.arange(1,5)   # Numpy array range same a s python list

array([1, 2, 3, 4])

In [22]:
np.arange(1,5,2)  # Range 1 to 5 # last parameter is step. Here, it's 2 . So it will be 1+2=3, 3+2...

array([1, 3])

In [23]:
np.linspace(1,5,10) # Linearly spacing. It will take range of 1 to 5 and generate 10 numbers between this

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [24]:
np.linspace(1,5,5) 

array([1., 2., 3., 4., 5.])

In [26]:
b.reshape(2,3) # it will reshape to 2 rows and 3 columns

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
oneD=b.ravel() # Ravel flatten to 1D array
oneD

array([1, 2, 3, 4, 5, 6])

In [28]:
b.min()

1

In [29]:
b.max()

6

In [30]:
b.sum()

21

In [31]:
b.sum(axis=0)    # Using axis

array([ 9, 12])

In [32]:
b.sum(axis=1) 

array([ 3,  7, 11])

In [33]:
np.sqrt(b)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [34]:
np.std(b)     # Standar Deviation

1.707825127659933

In [35]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [36]:
a+b    # Convinient in computation

array([[ 6,  8],
       [10, 12]])

In [37]:
a*b

array([[ 5, 12],
       [21, 32]])

In [38]:
a.dot(b)  # Matrix dot product

array([[19, 22],
       [43, 50]])