# Indexing, Slicing & Boolean arrays

In [1]:
import numpy as np

In [2]:
n=[6,7,8]
n[:2] # slicing in python

[6, 7]

In [3]:
n[-1]  # indexing access

8

In [4]:
a=np.array([6,7,8])
a[0:2]

array([6, 7])

In [7]:
a[-1]

8

In [8]:
ma=np.array([[1,2,3],[4,5,6],[7,8,9]])  # Multidimensional array

In [9]:
ma

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
ma[1,2]  #(1st row, 2nd column)

6

In [11]:
ma[0:2,2]    # 0 to 2nd rows, and 2nd index element

array([3, 6])

In [14]:
ma[-1]

array([7, 8, 9])

In [15]:
ma[-1, 0:2]

array([7, 8])

In [16]:
ma[:,1:3]  # accessing columns.":" will go through all rows

array([[2, 3],
       [5, 6],
       [8, 9]])

In [17]:
ma # sort of table

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
for row in ma:   # iterate through rows
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [20]:
# Flatten the list and print every cell

for cell in ma.flat:   # flattening to 1D & iterate
    print(cell)

1
2
3
4
5
6
7
8
9


In [23]:
reshapeArray=np.arange(6).reshape(3,2)   # Taking 6 range and reshaping to 3,2 dimension
reshapeArray

array([[0, 1],
       [2, 3],
       [4, 5]])

In [24]:
reshapeArray2=np.arange(6,12).reshape(3,2) 
reshapeArray2

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [25]:
np.vstack((reshapeArray,reshapeArray2))    # touple argument to stack two numpy array stack # Vertical stack

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [26]:
np.hstack((reshapeArray,reshapeArray2))   #  Horizontal stack

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [30]:
new= np.arange(30).reshape(2,15)
new

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [31]:
np.hsplit(new,3)   # Horizonal split to 3 new array

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [32]:
result=np.hsplit(new,3)
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [33]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [35]:
 r=np.vsplit(new,2)   # Vertical split to 2 new array

In [36]:
 r[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [37]:
r[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [39]:
a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
b= a > 4           # Using Boolean operation

In [41]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [42]:
a[b]    # It will only return true values of numpy array

array([ 5,  6,  7,  8,  9, 10, 11])

In [43]:
a[b] = -1  # any element that greater than 4 (b=a>4), will be replace by -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])