# Iterate using nditer

In [2]:
import numpy as np

In [3]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
# Iterate

for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [5]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [6]:
for cell in a.flatten():  # using 1 loop
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [7]:
for x in np.nditer(a,order='C'):
    print(x)


0
1
2
3
4
5
6
7
8
9
10
11


In [8]:
for x in np.nditer(a,order='F'):  # Fortan order
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [10]:
# Print entire column in each iteration

for x in np.nditer(a,order='F',flags=['external_loop']):  # Fortan order
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [11]:
# Iterate through entire array and modify the element

for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=x*x                        #square and modify the original array
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [13]:
# iterate two numpy array simultaneously

b=np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [14]:
for x,y in np.nditer([a,b]):
    print(x,y)      # iterating array a and b

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
